name: CI/CD Docker Deploy

# Se ejecuta en cada push a main
on:
  push:
    branches: [ "main" ]

jobs:

  # Job que va a construir y subir la imagen de Docker
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Recupera todo el historial

    - name: Set up Docker Buildx            # Aca se configura Docker Buildx para construir imagenes
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub            # Inicia sesion en Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image     # Construye y sube la imagen
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flask_app:latest
 

# Job para el despliegue remoto usando SSH
  deploy:
    runs-on: ubuntu-latest
    needs: build  # Este job depende del job "build"

    steps:
    - name: Deploy to VM via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}        # HOST publicado por NGROK 
        username: ${{ secrets.VM_USER }}    # Usuario SSH
        password: ${{ secrets.VM_PASS }}   
        port: ${{ secrets.PORT }}           # PUERTO publicado por NGROK
        script: |
          echo "Desplegando la aplicación en la VM..."
          bash -c "
            cd /Users/pablonssss/appflask_des15/ 
            git pull origin main
            /usr/local/bin/docker-compose down
            /usr/local/bin/docker-compose pull
            /usr/local/bin/docker-compose up -d
          "

    - name: Expose Flask App with Ngrok
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        password: ${{ secrets.VM_PASS }}
        port: ${{ secrets.PORT }}
        script: |
          echo "Iniciando Ngrok para exponer la aplicación..."
          ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          nohup ngrok http 80 &
